### ISSUE TITLE
error during decompress the data set: "operation not permitted"

### ISSUE THREAD

**Issue by vwoloszyn** [TUB-NLP-OpenData/climate_change#2]
hi @eduardogc8,  could you have a look at the data? It's somehow corrupted... It says during the unpacking: "operation not permitted". (I have tried to download it multiple times)

**Comment by eduardogc8** [comment]
It seems normal here. I downloaded and loaded it in python normally.

I searched for "unpacking operation not permitted" and it seems to be a problem with the Mac.

https://truefire.zendesk.com/hc/en-us/articles/200200576-Can-t-Unzip-Operation-not-permitted-or-Decompression-Failed-Mac-

**Comment by vwoloszyn** [comment]
strange... can you run it properly here? : 
https://github.com/TUB-NLP-OpenData/climate_change/blob/master/code/Data_Acquisition_and_Understanding/statistics.ipynb
